# Generated by Django 5.1.2 on 2024-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePelicula', models.CharField(max_length=30)),
                ('ano', models.IntegerField(help_text=1990, max_length=4)),
                ('clasificacion', models.CharField(help_text='+13, +18', max_length=6)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
