# Generated by Django 5.1 on 2024-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='ano',
            field=models.IntegerField(help_text=1990),
        ),
    ]
